#For chat colors use '&' like every other plugin

server-startup:
  first-event-broadcast-enabled: true
  first-event-broadcast: '&cAn event will start in 20 minutes!'
  #Tick based, every 20 ticks = 1 seconds, so 100 ticks would be 5 seconds
  first-event-delay: 24000
  event-delay: 72000
  good-event-duration: 24000
  broadcast-event-running: true

server-event-broadcasts:
  double-ores:
    start-msg:
      - '&b&lDOUBLE ORES'
      - ''
      - '&7Dammit, why has nobody caught this pesky wizard yet? Look what he has done!'
      - '&fMining any ore will now give you double the rewards. Wizard… come on man. '
      - ''
      - '&7This event will last for &7&n20 Minutes.'
    end-msg:
      - '&7Double Ores has &cended!'
  double-xp:
    start-msg:
      - '&6&lDOUBLE XP'
      - ''
      - '&7Alright, who let the wizard out of his tower?'
      - '&fYou will now receive twice the experience from mob kills.'
      - ''
      - '&7This event will last for &7&n20 Minutes.'
    end-msg:
      - '&7Double XP has &cended!'
  double-mob-drops:
    start-msg:
      - '&2&lDOUBLE MOB-DROPS'
      - ''
      - '&7Recently, you have developed a hatred towards mobs!'
      - '&fAll mobs will now drop twice their loot. Perfect time to strike.'
      - ''
      - '&7This event will last for &7&n20 Minutes.'
    end-msg:
      - '&7Double Mob Drops has &cended!'
  insta-kill:
    start-msg:
      - '&4&lONE SHOT, ONE KILL'
      - ''
      - '&7The Evil Witches spell has been reversed.'
      - '&fAll mobs will now die in 1 hit from any item.'
      - ''
      - '&7This event will last for &7&n20 Minutes.'
    end-msg:
      - '&7Global Multiplier has &cended!'
    amount: 2.0
  angle-event:
    start-msg:
      - '&d&lMAGIC TRICK'
      - ''
      - '&7Alright, who let the Alchemist finish his training early?'
      - '&fYou now have Haste II & Speed II. He needs more training.'
      - ''
      - '&7This event will last for &7&n20 Minutes.'
    end-msg:
      - '&7Angel Event has &cended!'