name: GlobalEvents
main: me.pray.globalevents.GlobalEvents
version: 1.1
api-version: 1.16
depend: [WorldGuard]
commands:
  startevents:
    description: Start the global (re-occuring) events
  stopevents:
    description: Stop the global (re-occuring) events
  globaleventsreload:
    description: Re-loads the configuration file
    aliases: [gereload, ger]
